"""Stable blocked-reason strings for social-autonomy ticks."""

from __future__ import annotations

from src.ham.social_autonomy.tick import (
    AUTONOMY_ACTION_NOT_ALLOWED,
    AUTONOMY_CADENCE_NOT_DUE,
    AUTONOMY_CAP_EXCEEDED,
    AUTONOMY_CAP_TRACKING_UNAVAILABLE,
    AUTONOMY_CAP_ZERO,
    AUTONOMY_CHANNEL_DISABLED,
    AUTONOMY_CHANNEL_UNAVAILABLE,
    AUTONOMY_EMERGENCY_STOP,
    AUTONOMY_FORBIDDEN_TOPIC_MATCHED,
    AUTONOMY_PAYLOAD_EMPTY_OR_TOO_SHORT,
    AUTONOMY_PROFILE_MISSING,
    AUTONOMY_PROFILE_NOT_RUNNING,
    AUTONOMY_QUIET_HOURS_ACTIVE,
    AUTONOMY_SAFETY_RULE_UNENFORCED,
    AUTONOMY_SAFETY_RULE_VIOLATION,
    BLOCKED_REASON_CODES,
)

__all__ = [
    "AUTONOMY_ACTION_NOT_ALLOWED",
    "AUTONOMY_CADENCE_NOT_DUE",
    "AUTONOMY_CAP_EXCEEDED",
    "AUTONOMY_CAP_TRACKING_UNAVAILABLE",
    "AUTONOMY_CAP_ZERO",
    "AUTONOMY_CHANNEL_DISABLED",
    "AUTONOMY_CHANNEL_UNAVAILABLE",
    "AUTONOMY_EMERGENCY_STOP",
    "AUTONOMY_FORBIDDEN_TOPIC_MATCHED",
    "AUTONOMY_PAYLOAD_EMPTY_OR_TOO_SHORT",
    "AUTONOMY_PROFILE_MISSING",
    "AUTONOMY_PROFILE_NOT_RUNNING",
    "AUTONOMY_QUIET_HOURS_ACTIVE",
    "AUTONOMY_SAFETY_RULE_UNENFORCED",
    "AUTONOMY_SAFETY_RULE_VIOLATION",
    "BLOCKED_REASON_CODES",
]
