// Generated by src/ham/builder_test_generator.py — do not edit by hand.
// plan_id: pln_golden_destr
// workspace_id: ws_g
// preview_url: http://localhost:3000
const { test, expect } = require('@playwright/test');

test.describe('HAM Builder verification — pln_golden_destr', () => {

  test('Step 1: Delete table', async ({ page }) => {
    await page.goto('http://localhost:3000', { waitUntil: 'domcontentloaded' });
    // Remove the data table
    await expect(page.getByRole('table').first()).toBeVisible();
    await expect(page.locator('body')).not.toBeEmpty();
  });

});
