// Generated by src/ham/builder_test_generator.py — do not edit by hand.
// plan_id: pln_golden_multi
// workspace_id: ws_g
// preview_url: http://localhost:3000
const { test, expect } = require('@playwright/test');

test.describe('HAM Builder verification — pln_golden_multi', () => {

  test('Step 1: Create heading', async ({ page }) => {
    await page.goto('http://localhost:3000', { waitUntil: 'domcontentloaded' });
    // Add page heading
    await expect(page.getByRole('heading').first()).toBeVisible();
    await expect(page.locator('body')).not.toBeEmpty();
  });

  test('Step 2: Add form', async ({ page }) => {
    await page.goto('http://localhost:3000', { waitUntil: 'domcontentloaded' });
    // Create input form
    await expect(page.getByRole('textbox').first()).toBeVisible();
    await expect(page.locator('body')).not.toBeEmpty();
  });

  test('Step 3: Add link', async ({ page }) => {
    await page.goto('http://localhost:3000', { waitUntil: 'domcontentloaded' });
    // Insert navigation link
    await expect(page.getByRole('link').first()).toBeVisible();
    await expect(page.locator('body')).not.toBeEmpty();
  });

});
