/** Product-facing labels for the settings-first Social cockpit (no API contract). */

export const SOCIAL_COPY = {
  sectionsSubtitle: "Configure Ham’s voice, channel settings, and guarded actions in one place.",
  overviewProductSummary: "What Ham is configured to do",
  overviewRhythm: "How often Ham can act",
  overviewHamStatus: "Active, paused, or blocked",
  overviewNextAction: "Next recommended action",
  overviewCanDoNow: "What Ham can do now",
  overviewNeedsSetup: "What needs setup",
  overviewAutopilot: "Autopilot state",
  overviewSafety: "Safety status",
  overviewPersona: "Persona status",
  overviewRecentActivity: "Recent activity",
  overviewAttention: "Channel attention",
  activityWhatHamDoing: "What Ham has been doing",
  activityRecentSuggestions: "Recent suggestions",
  activitySafetyRelevant: "Safety-relevant activity",
  activityTelemetryDetailsTitle: "Delivery and audit counts (technical)",
  activityTelemetryDetailsSummary: "Session snapshot metrics for support — not needed for daily operation",
  setupHostTokenTechnicalTitle: "Runtime host & credentials (technical)",
  setupHostTokenTechnicalSummary: "Token names and bridge details for operators",
  telegramPacingTechnicalTitle: "Telegram pacing internals (technical)",
  telegramPacingTechnicalSummary: "Cooldown windows and reasons from latest previews",
  channelProductSummary: "Channel summary",
  channelPacingAdvanced: "Pacing and limits (advanced)",
  channelPostingSettings: "Posting",
  channelReplySettings: "Replies",
  channelSafetySettings: "Safety",
  channelRecentActions: "Recent actions",
  channelSetupStatus: "Setup status",
  advancedDetailsSummary: "Advanced technical proof",
  technicalProofTabLabel: "Advanced technical proof",
  technicalProofWarning:
    "Technical proof for debugging and audit. Not needed for normal operation.",
  digestProtectionTitle: "Digest protection",
  voiceLockPlain: "Ham’s voice is fingerprinted so previews and sends stay tied to the same persona.",
} as const;
