"""Playwright test generator for the verifier loop — Phase 1 #5 (Tier 1 #19).

Pure function ``generate(plan, preview_url) -> str`` produces a deterministic,
golden-file-testable Playwright test source from a Plan. No LLM calls, no I/O.

The generator builds lightweight smoke assertions from the Plan's Step titles
and descriptions so the verifier can confirm the app at least renders without
a blank page or obvious error state.

Spec: docs/MANUS_PARITY_ROADMAP.md § Tier 1 #19
"""

from __future__ import annotations

import re
import textwrap

from src.ham.builder_plan import Plan

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_SLUG_RE = re.compile(r"[^a-zA-Z0-9]+")


def _slugify(text: str, max_len: int = 40) -> str:
    slug = _SLUG_RE.sub("_", text.strip().lower()).strip("_")[:max_len]
    return slug or "step"


def _escape_js_string(text: str) -> str:
    return text.replace("\\", "\\\\").replace("'", "\\'").replace("\n", " ")


def _keyword_assertions(title: str, description: str) -> list[str]:
    """Return Playwright assertion lines inferred from step text.

    Heuristic: look for UI nouns in title/description and generate
    ``expect(page.getByText/getByRole/locator).toBeVisible()`` guards.
    The goal is a smoke test that detects blank pages and hard crashes,
    not a full end-to-end test suite.
    """
    combined = f"{title} {description}".lower()
    assertions: list[str] = []

    keyword_roles = [
        ("button", "button"),
        ("submit", "button"),
        ("input", "textbox"),
        ("form", "form"),
        ("link", "link"),
        ("navigation", "navigation"),
        ("heading", "heading"),
        ("table", "table"),
    ]
    for keyword, role in keyword_roles:
        if keyword in combined:
            assertions.append(
                f"  await expect(page.getByRole('{role}').first()).toBeVisible();"
            )
            break

    # Generic: page should not be blank
    assertions.append("  await expect(page.locator('body')).not.toBeEmpty();")
    return assertions


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate(plan: Plan, preview_url: str) -> str:
    """Return a self-contained Playwright test source string.

    The generated test:
    - Navigates to ``preview_url``
    - Asserts the page loaded (no hard error / blank body)
    - Emits one smoke assertion per Step inferred from step text

    Deterministic: same ``plan`` + ``preview_url`` always produce the same output.
    """
    url_esc = _escape_js_string(preview_url)
    plan_id_esc = _escape_js_string(plan.plan_id)
    workspace_id_esc = _escape_js_string(plan.workspace_id)

    lines: list[str] = [
        "// Generated by src/ham/builder_test_generator.py \u2014 do not edit by hand.",
        f"// plan_id: {plan_id_esc}",
        f"// workspace_id: {workspace_id_esc}",
        f"// preview_url: {url_esc}",
        "const { test, expect } = require('@playwright/test');",
        "",
        f"test.describe('HAM Builder verification \u2014 {plan_id_esc}', () => {{",
        "",
    ]

    for i, step in enumerate(plan.steps):
        title_esc = _escape_js_string(step.title)
        desc_esc = _escape_js_string(step.description[:100])
        assertions = _keyword_assertions(step.title, step.description)
        lines.append(f"  test('Step {i + 1}: {title_esc}', async ({{ page }}) => {{")
        lines.append(f"    await page.goto('{url_esc}', {{ waitUntil: 'domcontentloaded' }});")
        lines.append(f"    // {desc_esc}")
        for assertion in assertions:
            lines.append(f"    {assertion.strip()}")
        lines.append("  });")
        lines.append("")

    lines.append("});")
    lines.append("")

    return "\n".join(lines)
