"""Build audit-oriented PDF exports for persisted chat sessions (transcript only)."""
from __future__ import annotations

from datetime import datetime, timezone
from io import BytesIO
from xml.sax.saxutils import escape

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

from src.ham.chat_user_content import try_parse_stored_v2, plain_text_for_operator
from src.ham.pdf_export_sanitizer import redact_for_pdf_export


def _utc_export_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _format_user_message_for_pdf(raw_content: str) -> str:
    """Operator-safe user text + attachment filenames (no ids, no extracted bodies)."""
    base = plain_text_for_operator(raw_content)
    v2 = try_parse_stored_v2(raw_content)
    if v2 is None:
        return base
    names: list[str] = []
    for a in v2.get("attachments") or []:
        if isinstance(a, dict):
            n = str(a.get("name") or "").strip()
            if n:
                names.append(n)
    if not names:
        return base
    extra = "Attachments referenced (names only): " + ", ".join(names)
    if base.strip():
        return f"{base}\n{extra}"
    return extra


def _format_turn_body(role: str, content: str) -> str:
    if role == "user":
        body = _format_user_message_for_pdf(content)
    else:
        body = content or ""
    return redact_for_pdf_export(body)


def _paragraph_from_text(text: str, style: ParagraphStyle) -> Paragraph:
    """ReportLab Paragraph with newlines as <br/>."""
    esc = escape(text or "")
    esc = esc.replace("\n", "<br/>")
    return Paragraph(esc, style)


def render_chat_transcript_pdf_bytes(
    *,
    session_id: str,
    created_at: str | None,
    turns: list[tuple[str, str]],
) -> bytes:
    """
    ``turns`` — ``(role, content)`` in order; ``content`` is persisted session text
    (may include ham_chat_user_v2 JSON for user turns).
    """
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        rightMargin=inch * 0.75,
        leftMargin=inch * 0.75,
        topMargin=inch * 0.75,
        bottomMargin=inch * 0.75,
        title="HAM chat transcript",
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "ExpTitle",
        parent=styles["Heading1"],
        fontSize=16,
        spaceAfter=12,
    )
    meta_style = ParagraphStyle(
        "ExpMeta",
        parent=styles["Normal"],
        fontSize=9,
        textColor="#444444",
        spaceAfter=6,
    )
    role_style = ParagraphStyle(
        "ExpRole",
        parent=styles["Heading2"],
        fontSize=11,
        spaceBefore=10,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "ExpBody",
        parent=styles["Normal"],
        fontSize=10,
        leading=13,
        spaceAfter=8,
    )
    footer_style = ParagraphStyle(
        "ExpFoot",
        parent=styles["Normal"],
        fontSize=8,
        textColor="#666666",
        spaceBefore=18,
    )

    story: list = []
    story.append(Paragraph("HAM — Chat transcript export", title_style))
    story.append(
        _paragraph_from_text(
            f"Session id: {session_id}\n"
            f"Session created: {created_at or '—'}\n"
            f"Exported (UTC): {_utc_export_stamp()}",
            meta_style,
        ),
    )
    story.append(Spacer(1, 0.1 * inch))

    for role, content in turns:
        r = (role or "").strip().lower()
        label = (
            "User"
            if r == "user"
            else "Assistant"
            if r == "assistant"
            else ((role or "message").strip().title() or "Message")
        )
        story.append(Paragraph(escape(label), role_style))
        body = _format_turn_body(r, content)
        story.append(_paragraph_from_text(body, body_style))

    story.append(
        _paragraph_from_text(
            "Generated by HAM from stored transcript. "
            "Does not include raw attachment bytes or storage locations.",
            footer_style,
        ),
    )
    doc.build(story)
    return buf.getvalue()
